package ti4.async.bot.game.elements;

public enum CardType {
	ACTION_CARD, PROMISSORY_NOTE, SECRET_OBJECTIVE, AGENDA, STAGE_1_OBJECTIVE, STAGE_2_OBJECTIVE,
	EXPLORATION_CULTURAL, EXPLORATION_HAZARDOUS, EXPLORATION_FRONTIER, EXPLORATION_INDUSTRIAL, RELIC;
}